### ISSUE TITLE
Awesome use of the re lib!

### ISSUE THREAD

**Issue by jthompson18** [the872/parser330#3]
@the872  Awesome use of the re lib! Thank you for using re.findall() instead of re.sub() that was used in the original ttp project. findall is easier to read and the response is a list versus a string of matches. Its more usable and flexible.  Good test coverage too.

Now for my standard thought question:
Where do you see this living in a complete system? Did you have this in mind when writing this code and did it influence any of your development choices?

**Comment by the872** [comment]
re.findall() certainly made more sense to use for the reasons stated.

Regarding your question, I would say the code is pretty flexible in terms of application. I certainly kept the larger picture in mind and is why I didn't simply import [ttp](https://github.com/edburnett/twitter-text-python) and write the output. I kept the code as simple as I could (although I have learned that my regex could be improved a bit) but also thorough so it could run effectively. 

If I was to implement this into a larger project, the first thing I would do is remove some of the tools that are not needed any longer or that I did't use, particularly the ones that are strictly used to set the python project up. Following that I would clean the code up as much as possible, removing all redundancy and then I believe it would be ready to implement into a variety of larger projects. Things like Twitter sentiment programs come to mind but also various machine learning projects that rely on properly parsing a Twitter Feed/s could certainly see benefit out of this code. Plus it is in Python so that alone is very flexible in terms of where it can be applied to.
